import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { zhCN } from "@clerk/localizations";
import { NavigationBar } from "@/components/NavigationBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "IELTS Fan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body suppressHydrationWarning>
        <ClerkProvider localization={zhCN}>
          <NavigationBar />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
